name: Bump casks on schedule or request

on:
  workflow_dispatch:
  schedule:
    # Every 3 hours 23 minutes past the hour
    - cron: "23 */3 * * *"

permissions: {}

jobs:
  autobump:
    if: github.repository == 'maxinchun5/homebrew-community-cask'
    env:
      HOMEBREW_DEVELOPER: 1
    runs-on: macos-26
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@f8d4222eb633e65c2a0157383cf80861fc7fae7f # 2026.09.07.1

      - name: Configure Git user
        id: git_setup
        uses: Homebrew/actions/git-user-config@f8d4222eb633e65c2a0157383cf80861fc7fae7f # 2026.09.07.1

      - name: Bump casks
        id: autobump
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GIT_COMMITTER_NAME: ${{ steps.git_setup.outputs.name }}
          HOMEBREW_GIT_COMMITTER_EMAIL: ${{ steps.git_setup.outputs.email }}
          TAP_NAME: ${{ steps.set-up-homebrew.outputs.tap-name }}
        continue-on-error: true
        run: brew bump --no-fork --open-pr --tap="${TAP_NAME}"
